{% set name = "deid" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc6874d7d20c4e18df295e2a8f2d2eb3442d93520bd20469b90ae1717247bf8a

build:
  number: 0
  noarch: python
  entry_points:
    - deid=deid.main:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - pydicom >=1.3.0
    - python-dateutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - deid
    - deid.config
    - deid.config.utils
    - deid.config.standards
    - deid.dicom
    - deid.dicom.actions
    - deid.dicom.fields
    - deid.dicom.filter
    - deid.dicom.header
    - deid.dicom.tags
    - deid.dicom.utils
    - deid.dicom.validate
    - deid.dicom.pixels
    - deid.dicom.pixels.clean
    - deid.dicom.pixels.detect
    - deid.logger
    - deid.logger.progress
    - deid.logger.message
    - deid.main
    - deid.main.inspect
    - deid.main.identifiers
    - deid.utils
    - deid.utils.actions
    - deid.utils.fileio
  commands:
    - deid --help

about:
  home: https://www.github.com/pydicom/deid
  license: MIT
  license_family: OTHER
  license_file: LICENSE
  summary: best effort anonymization for dicom images with Python
  doc_url: https://pydicom.github.io/deid/
  dev_url: https://github.com/pydicom/deid

extra:
  recipe-maintainers:
    - vsoch
