travis:
  secure:
    BINSTAR_TOKEN: U7p8PiZAEuC8hBgzWn4zFtIFPmfUTvVk8sop5ek9PgRhapEPukK1lL1Fh06XBslbksIvGgxW7PWCtw+FpHFv9sd16CrK/crUob3I5R269c/q3gzBoCMHhm8ajSKvT4RxR8F2SmMskLtYdGEv+g71g/PbeIRSywUgyBjiHZtgVFymPQaoj2udsiUqdMD+XwEuAMZ1c1hEZWYu1fRDXQHQ7b9MNML1+haAdHEVC2vWk216lNUgK9g1wfB0SX3AltrRfEG492DQsW43dFW46ZsC9pwTZGKIZ5qKiqHD+XAxDoiMquhOpEgP6AimdtImbnZf2/6ut6Bbf3Bv67hFUnOoUBRMv7qtkwtlXVfUwO/c78eqd3htQN5siGkgqef+uNnssD5qy0hkBdMciuFUpZPfQ+WRFaKyBOsd/kWX1fi0wpMabe4BMrKE2vR96sThetIspv+0sGKx3R5bhMn3w9SR1pN4vOmpkgycwgGbVcF/ASzTYEeEwApSTILNm+rqL/k6X0CwP2dWImdPC1JfC1/1cqxA+Och655+CUo5z2QkTrHJpFKoRsmT/SxBqAWl8vPtek3zFbZ5t2aquDyoy4+ti0T6L8uvcz6nSxNlpyn9zrlS5WnmF5kDVd9FF5nOAtmeYqCNeGZxX5PSo1iDmrNwuA5p57K4v/7fSt4mtJZFuV4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
