travis:
  secure:
    BINSTAR_TOKEN: PplO2PgcjWPSRTGk5xwxR522UVcXOx4OESC2AZ4Q8iVK1CUUp/N4eBORNAuXpzT8wihkSclnwdkypY+asH7xbMG8DwDPh6quNsGfcQZnyDRT9vhxlyu1yI/y1ymW1H1Jaw7U7rKsCl1uWsNUoPRtEFa3txy+7YRGjx2gVsrWW4mhm+3IBLJ+CTFTEjZkbxDkwIzPllDRqbtLSp0akT9VSgoyOiEA2iCuRjvF2boiTe81se3++sSxte5bpHypsFln4XFO2JUPaO9XlO7InU5YA9kdnvtj6Mo1TjR+fHtwQKadGcOGZ1XoMJTdKM62sCi6xIML3uev1V9PEBh8p5A1O6kn4f2Oe4JHJCulyKmxbpODWvWu6+F73b1Ocf9ofmXLiP7PqAaExf7QnN8kLPZouVP0qLl5qom1SyyfjLVaCfkk3Dj6J1WVvJUT1unAiYBkP+AiR2KbZ7w4qEKrgSaGw9lS0v5zSGF0ydfvmchnIard0ep4e4KAh2k5WTAUQK0k69lQmBZzHvP9zpUfjlGHTqUFWNC4o6+VSSQDqNcvOXZlTSwackyaavQ3Oz1GC2yd+kW46+rdfIi7qFlz5az92aMAY2bgSxbqujYaQ5Ln7UK1effH+Ew0qZ/TUQFb5mgRYPOM749Fi6/SXsBP/ye0/LhiJ458gfUytrhqG+NSRYo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
